const slovak = {
  "Filters": "Filtre",
  "About the map": "O mape",
  "Selected area ({radius} km radius)": "Vybraná oblasť (okruh {radius} km)",
  "No concerts match this location": "Pre túto lokalitu nie sú koncerty",
  "Show the map area or try another date.": "Zobrazte oblasť na mape alebo skúste iný dátum.",
  "In this area": "V tejto oblasti",
  "Back to map": "Späť na mapu",
  "Show concerts": "Zobraziť koncerty",
  "Full programme": "Celý program",
  "Done": "Hotovo",
  "Radius": "Okolie",
  "Custom…": "Vlastné…",
  "Radius in km": "Okolie v km",
  "Set": "Nastaviť",
  "Straight-line distance from the city centre.": "Vzdušná vzdialenosť od centra mesta.",
  "Only concerts in Slovakia": "Iba koncerty na Slovensku",
  "Map": "Mapa",
  "Increase distance": "Zväčšiť vzdialenosť",
  "Concert map": "Mapa koncertov",
  "Concert map. Use arrow keys to pan, plus and minus to zoom.": "Mapa koncertov. Posúvajte šípkami, približujte a odďaľujte klávesmi plus a mínus.",
  "Map tiles could not be loaded.": "Mapové podklady sa nepodarilo načítať.",
  "Loading map…": "Načítava sa mapa…",
  "concerts": "koncertov",
  "{cities} cities · {count} concerts. Zoom in.": "{cities} miest · {count} koncertov. Priblížiť.",
  "Map of classical music concerts": "Mapa koncertov klasickej hudby",
  "Explore concerts by scrolling the map.": "Objavuj koncerty posúvaním sa po mape.",
  "List view": "Zobraziť zoznam",
  "Go to city": "Prejsť na mesto",
  "Search cities": "Hľadať mestá",
  "Search cities worldwide": "Hľadať mestá vo svete",
  "Explore concerts on the map": "Objavujte koncerty na mape",
  "{count} concerts across {cities} cities": "{count} koncertov v {cities} mestách",
  "Concert programme": "Koncertný program",
  "In this view": "V tejto oblasti",
  "Show area": "Celá oblasť",
  "{count} concerts": "Počet koncertov: {count}",
  "No concerts in this view": "V tejto oblasti nie sú koncerty",
  "Move the map, zoom out, or try another date.": "Posuňte mapu, oddiaľte ju alebo skúste iný dátum.",
  "Opens in a new tab": "Otvorí sa na novej karte",
  "Markers show city locations, not individual venues.": "Značky označujú polohu miest, nie jednotlivých sál.",
  "Explore upcoming classical music concerts on an interactive world map.": "Objavujte nadchádzajúce koncerty klasickej hudby na interaktívnej mape sveta.",
  "Map area": "Oblasť na mape",
  "Remove map area": "Zrušiť oblasť na mape",

  "Zoom in": "Priblížiť",
  "Zoom out": "Oddialiť",
  "Date unavailable": "Dátum nie je k dispozícii",
  "Matches filter": "Vyhovuje filtru",
  "Find concerts featuring {work}": "Nájsť koncerty s dielom {work}",
  "Concert filters": "Filtre koncertov",
  "Country": "Krajina",
  "Loading countries…": "Načítavajú sa krajiny…",
  "Countries unavailable": "Krajiny nie sú dostupné",
  "All countries": "Všetky krajiny",
  "No matching countries": "Žiadne vyhovujúce krajiny",
  "Countries could not be loaded.": "Krajiny sa nepodarilo načítať.",
  "Try again": "Skúsiť znova",
  "City": "Mesto",
  "Any city": "Všetky mestá",
  "When": "Kedy",
  "Any upcoming date": "Kedykoľvek",
  "Today": "Dnes",
  "This week": "Tento týždeň",
  "This weekend": "Tento víkend",
  "Custom dates": "Vlastný dátum",
  "From": "Od",
  "To": "Do",
  "Until": "Do",
  "Composer or work": "Skladateľ alebo dielo",
  "Composer": "Skladateľ",
  "Search composers": "Hľadať skladateľov",
  "Work": "Dielo",
  "Search works or composers": "Hľadať diela alebo skladateľov",
  "Clear filters": "Zrušiť filtre",
  "Remove {label} filter": "Odstrániť filter {label}",
  "Change city…": "Zmeniť mesto…",
  "Add another…": "Pridať ďalší…",
  "Options could not be loaded.": "Možnosti sa nepodarilo načítať.",
  "Searching…": "Vyhľadáva sa…",
  "No matching options.": "Žiadne vyhovujúce možnosti.",
  "Options could not be loaded. Try again.": "Možnosti sa nepodarilo načítať. Skúste to znova.",
  "Searching for options.": "Vyhľadávajú sa možnosti.",
  "Work {id}": "Dielo {id}",
  "Updating…": "Aktualizuje sa…",
  "Concerts could not be loaded": "Koncerty sa nepodarilo načítať",
  "Try again, or adjust the selected filters.": "Skúste to znova alebo upravte vybrané filtre.",
  "Retry": "Skúsiť znova",
  "Concert pages": "Stránky koncertov",
  "Previous page": "Predchádzajúca stránka",
  "Next page": "Ďalšia stránka",
  "Page {page}": "Stránka {page}",
  "No upcoming concerts listed in {city}.": "Pre mesto {city} momentálne nie sú uvedené žiadne nadchádzajúce koncerty.",
  "No upcoming concerts match these filters.": "Vybraným filtrom nezodpovedajú žiadne nadchádzajúce koncerty.",
  "Try any date": "Zobraziť všetky dátumy",
  "Remove music filters": "Zrušiť filtre hudby",
  "Browse all concerts": "Zobraziť všetky koncerty",
  "Browse concerts in {country}": "Zobraziť koncerty v krajine {country}",
  "No concerts": "Žiadne koncerty",
  "{total} {concerts} · showing {first}–{last}": "{total} {concerts} · zobrazené {first}–{last}",
  "Discover upcoming classical music concerts in {city}, {country}.": "Prehľad nadchádzajúcich koncertov klasickej hudby: {city}, {country}.",
  " (opens in a new tab)": " (otvorí sa na novej karte)",
  "Visit {source} website": "Navštíviť web {source}"
}

export function createConcertText(locale = 'en-GB') {
  const sk = locale === 'sk-SK'
  const rules = new Intl.PluralRules(sk ? 'sk' : 'en')
  const forms = sk
    ? { concert: ['koncert', 'koncerty', 'koncertov'], filter: ['aktívny filter', 'aktívne filtre', 'aktívnych filtrov'], option: ['možnosť', 'možnosti', 'možností'] }
    : { concert: ['concert', 'concerts', 'concerts'], filter: ['active filter', 'active filters', 'active filters'], option: ['option', 'options', 'options'] }
  const t = (text, values = {}) => (sk ? slovak[text] || text : text).replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? ''))
  const plural = (kind, count) => forms[kind][{ one: 0, few: 1 }[rules.select(count)] ?? 2]
  const activeFilters = count => `${count} ${plural('filter', count)}`
  const availableOptions = count => sk ? `Dostupné možnosti: ${count}.` : `${count} ${plural('option', count)} available.`
  return { locale, t, plural, activeFilters, availableOptions }
}
